services:
  app:
    build: .
    container_name: mood_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env  
    restart: always

  # worker:
  #   build: .
  #   container_name: mood_worker
  #   command: python worker.py
  #   env_file:
  #     - .env
  #   restart: always
