import random

def overall_mood(energy):
    energyMessages = {
    1: [
        "Your overall mood today feels completely drained.",
        "You reported feeling very low on energy today.",
        "You're running on empty right now — it's okay to rest.",
        "Today feels like a total recharge day — take it slow.",
        "Energy is at rock bottom — a recovery moment might help."
        "You’re completely drained today.",
        "Your tank is totally empty — take it easy.",
        "Energy is rock bottom right now.",
        "This is a full rest-and-recover day.",
        "You might feel completely out of steam.",
        "Today feels heavy and exhausting.",
        "Energy is at zero — perfect time to slow down.",
        "Your system needs serious rest today.",
        "This is as low as it gets — recharge mode ON.",
        "Even small tasks may feel overwhelming right now.",
        "You're running on fumes — deep rest matters.",
        "Today calls for absolute stillness.",
        "Your energy meter is flashing red.",
        "Your body and mind might be screaming for a pause.",
        "Today feels like a full stop — and that’s okay.",
        "You're in deep low-power mode right now.",
        "Energy bottomed out — no need to push today.",
        "Everything might feel like climbing a mountain today.",
        "You're in full recovery territory right now.",
        "This is one of those complete shutdown days — be kind to yourself."
    ],
    2: ["Your energy is very low today.",
        "You might be feeling exhausted or worn out right now.",
        "Today's check-in shows you're running quite low.",
        "Energy levels are at the low end — self-care could help.",
        "This is a tough energy day — be gentle with yourself.",
        "Your energy is very low today.",
        "You're running at a slow crawl right now.",
        "Energy is fragile — tread gently today.",
        "Everything may feel like it takes extra effort.",
        "This is a very slow-moving kind of day.",
        "You're running close to empty — light tasks only.",
        "Today might feel physically or mentally exhausting.",
        "Energy feels unstable — good time to pause.",
        "You're in low-battery mode right now.",
        "Your reserves are nearly tapped out.",
        "It’s okay if things move slowly today.",
        "This is a near-rest day — don’t overexert.",
        "You might feel like lying down all day.",
        "Even small wins might feel like big climbs.",
        "Your body is asking for downtime.",
        "Energy feels delicate — preserve what’s left.",
        "You're on the edge of burnout — take care.",
        "This is a quiet, low-output day.",
        "Every step might feel heavier than usual.",
        "You’re almost at rock bottom — recovery will help."
    ],
    3: [
        "Your energy is low today.",
        "You may feel tired or sluggish.",
        "This is a slow-moving kind of day.",
        "You’re not at your best, but you’re here.",
        "Energy feels dull — small steps count.",
        "You're dragging a bit, but still showing up.",
        "This is a low-focus, low-drive day.",
        "Even simple tasks may feel draining.",
        "You're taking it slow today.",
        "This is a below-average energy day.",
        "Energy feels flat — not terrible, not great.",
        "You might need an extra push to get moving.",
        "Motivation may be hard to find right now.",
        "This is a good day for light activities only.",
        "You're a bit undercharged today.",
        "Energy is dipping but not gone entirely.",
        "Your body is signaling a need to slow down.",
        "Today calls for gentle effort.",
        "You might be feeling sluggish or foggy.",
        "Energy is low but still present — a light boost may help.",
        "You seem to have low energy today.",
        "Energy feels sluggish — maybe a good time to recharge.",
        "Today's check-in points to a slower-paced mood.",
        "You might be feeling a bit run down right now.",
        "Energy is dipping — a short walk or rest could help reset."
        ],
    4: [
        "Your energy is slightly below average.",
        "You feel a little slow today.",
        "This is a quiet, slightly low day.",
        "Energy is soft but steady.",
        "You're not at peak, but not fully drained either.",
        "Today feels like a low-pressure day.",
        "You're slightly tired — nothing too heavy.",
        "Energy is calm but not high.",
        "You're in a bit of a slump but functional.",
        "This is a take-it-easy kind of day.",
        "You might move slower than usual today.",
        "Energy is muted, not gone.",
        "You’re coasting just under neutral right now.",
        "This is a mellow energy state.",
        "You’re a little off your usual rhythm.",
        "Energy feels like it’s saving up for later.",
        "You’re a touch sluggish today, but still moving.",
        "This is a quiet, introspective mood.",
        "Energy is present, just softer than normal.",
        "You're in low gear but still rolling.",
        "Your energy is slightly below normal today.",
        "Today's check-in feels just a bit low-energy.",
        "Energy is on the quieter side — maybe take things easy.",
        "You might be feeling a little tired or unmotivated.",
        "This is a softer energy day — not too low, not too high."
        ],
    5: [
        "Your overall mood today feels neutral.",
        "You seem steady and balanced right now.",
        "Today's check-in shows you're in the middle — not too low, not too high.",
        "Energy feels level today, a nice steady state.",
        "You're sitting right at neutral — a solid baseline day.",
        "You’re balanced and steady today.",
        "Energy feels right in the middle — just enough.",
        "This is a neutral, even-keeled day.",
        "You're neither too low nor too high.",
        "Mood feels centered and stable.",
        "This is a good baseline day.",
        "You’re in a comfortable middle ground.",
        "Energy feels calm and balanced.",
        "You're steady and consistent today.",
        "Nothing extreme — just a regular day.",
        "You're in a state of equilibrium.",
        "This is your energy at baseline level.",
        "You’re coasting smoothly today.",
        "You’re in the middle zone — easygoing and level.",
        "Energy feels neither draining nor overwhelming.",
        "This is a balanced check-in — a good place to build from.",
        "You’re at your emotional midpoint today.",
        "Nothing dramatic — just a steady state.",
        "Energy is balanced and sustainable.",
        "You’re holding steady — right where you need to be."
        ],
    6: [
        "Your energy is slightly above neutral today.",
        "Today's check-in suggests a mild boost in mood.",
        "You're feeling just a bit more upbeat than usual.",
        "Energy feels light and steady today — a good sign.",
        "This is a gently positive day — calm but lifted.",
        "Your energy is slightly above average today.",
        "You might feel a bit lighter and brighter.",
        "Energy feels gently uplifting.",
        "You're a touch more motivated than usual.",
        "This is a calm but positive day.",
        "Energy is moving upward — a nice shift.",
        "You feel just a little more open and active.",
        "You're leaning toward the positive side today.",
        "Energy feels easy and smooth.",
        "You might feel quietly optimistic right now.",
        "This is a pleasant, mild-energy day.",
        "Energy has a subtle lift to it.",
        "You’re a notch above neutral today.",
        "This is a good state for creative work.",
        "Energy feels stable but warm.",
        "You're slightly more focused and present.",
        "You might feel small sparks of motivation.",
        "Energy is comfortably strong today.",
        "You're gently picking up momentum.",
        "This is a nice, easy-flow energy level."
        ],
    7: [
        "You seem to have good energy today.",
        "Today's mood reads as energized and upbeat.",
        "You're on the higher end of your energy range.",
        "This check-in points to a strong, positive day.",
        "Energy feels solid and ready for action.",
        "You have good energy today!",
        "This is a strong, positive day.",
        "Energy feels vibrant and active.",
        "You’re ready to get things done.",
        "Your mood is energized and lifted.",
        "You might feel motivated to take action today.",
        "Energy is flowing smoothly and strongly.",
        "You seem upbeat and ready.",
        "This is a productive energy level.",
        "You’re on the higher end of your range.",
        "Energy feels dynamic and stable.",
        "This is a good day for making progress.",
        "You’re in a go-getter mood today.",
        "Energy feels supportive for meaningful work.",
        "You’re operating in a positive state.",
        "This is a powerful mood for forward movement.",
        "Energy is healthy and active today.",
        "You might feel confident and capable right now.",
        "You’re in a good flow today.",
        "Energy is helping you stay focused and engaged."
    ],
    8: [
         "You're feeling very energized today!",
        "Today's check-in shows high energy and motivation.",
        "Energy levels are strong — a productive day ahead.",
        "This is a great day to tackle meaningful tasks.",
        "You're radiating positivity and drive right now.",
        "You're very energized today!",
        "This is a high-energy, action-driven day.",
        "You feel motivated and ready to move.",
        "Energy is strong and focused right now.",
        "You might feel excited and eager to act.",
        "This is a high-output kind of day.",
        "Energy feels powerful — great time to create.",
        "You’re operating at an impressive level today.",
        "This is a strong, motivated check-in.",
        "Energy feels bright and productive.",
        "You’re running with purpose right now.",
        "This is a go-big kind of day.",
        "You might feel unstoppable at the moment.",
        "Energy is pushing you toward peak focus.",
        "You’re radiating positivity and drive today.",
        "This is a high-performance mood state.",
        "Energy feels big and bright.",
        "You’re powered up and moving forward fast.",
        "You might feel extra inspired today.",
        "This is a very strong day for action."
        ],
    9: [
        "You're highly energized today!",
        "Today's check-in points to peak focus and motivation.",
        "Energy is at a powerful high — you can get a lot done.",
        "You're running at near-peak capacity right now.",
        "This is a strong, high-momentum day.",
        "You're highly energized today!",
        "This is near peak energy — full momentum ahead.",
        "Energy feels electric and powerful.",
        "You might feel unstoppable right now.",
        "This is an action-packed day waiting to happen.",
        "You’re charged up and fully alive today.",
        "Energy feels sharp and clear.",
        "This is a great day to chase big goals.",
        "You’re on fire today — use it well.",
        "Energy is near its peak right now.",
        "You might feel a rush of motivation today.",
        "This is a bold, confident energy state.",
        "You’re at the top of your focus range.",
        "Energy feels fast and powerful.",
        "You might feel like taking on challenges today.",
        "This is a day to push boundaries.",
        "Energy is in full swing right now.",
        "You’re hitting your stride.",
        "This is a strong performance day.",
        "Energy feels supercharged and ready."
        ],
    10: [
        "You're at peak energy today!",
        "This is a max-energy day — full of vitality and drive.",
        "Today's check-in shows you're completely charged up.",
        "You're at your absolute best right now — great time for big wins.",
        "Energy is sky-high — this is a top-performance day.",
        "You're at absolute peak energy today!",
        "This is max level — you’re unstoppable.",
        f"Energy is at {energy}% capacity right now.",
        "You might feel like conquering the world today.",
        "This is your top performance state.",
        "Energy is firing on all cylinders.",
        "You’re fully charged and ready for big wins.",
        "This is a flow-state kind of day.",
        "You might feel completely unstoppable right now.",
        "Energy is at its highest — strike while it’s hot.",
        "You’re performing at your absolute best today.",
        "This is a superpowered check-in.",
        "Energy feels limitless right now.",
        "You might feel euphoric or invincible today.",
        "This is a prime state for peak results.",
        "You’re overflowing with drive and focus.",
        "Energy is maxed out — time to go big.",
        "You’re in rare form today — take advantage of it.",
        "This is a legendary energy day.",
    "You’re at full strength — perfect for major action."
    ]}
    
    overall_mood_message = random.choice(energyMessages[energy])
    
    return overall_mood_message